### ISSUE TITLE
Create DB models

### ISSUE THREAD

**Issue by mlabisi** [thejavabeanteam/parkbud#1]
# Task: Use object-relational mapping to create database models for ParkBud
File(s)
- `server/db/models/*`
- `server/db/models/index.js`

Dependencies:
- crypto (read [this](https://www.geeksforgeeks.org/node-js-password-hashing-crypto-module/) up to where it says "Project Dependencies")
- sequelize (this is described pretty well in the dev guide below!)

[View Dev Guide](https://docs.google.com/document/d/1YsNZGSswVIu7BOlhjh83-xcVI6qBMH6D_bcGb27tnJM/edit)

**Comment by mlabisi** [comment]
Have you created and pushed a branch for this yet? If so, you can add a link to it as a comment. You can see an example of how I did it [here](https://github.com/thejavabeanteam/parkbud/issues/3#issuecomment-546741376).

@simba1998

**Comment by esassefa** [comment]
i have created a separate branch models to create and and edit my js files but i havent pushed anything yet since I'm still working on them

**Comment by mlabisi** [comment]
> i have created a separate branch models to create and and edit my js files but i havent pushed anything yet since I'm still working on them

@simba1998 
it's ok if you're still working on it! Just make sure to push it so that your github profile shows that you've been making commits!
